# Generated by Django 5.1.2 on 2024-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-creat',)},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='create',
            new_name='creat',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
