# Generated by Django 5.1.2 on 2024-10-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='creat',
            new_name='created',
        ),
    ]
